### PR TITLE
Fixes #1198 : Fix CI setup of fabric8 maven plugin

### LINKED ISSUE #1198: Fix CI setup of fabric8 maven plugin
Since we enabled Openshift 3.7 on Travis CI, we were facing lots of issues on Travis due to extremely slow regression tests and they were getting timeout because by default Travis gives a job a maximum time limit of 50 minutes to run. For more information see [here](https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts).

So due to this, we switched to CircleCI in the meantime. But now the build timeout limit of Travis has been extended; So we should revert back to Travis CI.

### PR DESCRIPTION
**Pull request by rohanKanojia**
#1198

### CODE REVIEW

**Comment by rohanKanojia** [comment]
It is going to run on 3.6.1 and 3.7.2 only. 


Build #1 : https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/builds/358723187
Build #2 : https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/builds/358715057
Build #3 : https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/builds/358794505
Build #4 : https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/builds/358829908

File: rt/src/test/java/io/fabric8/maven/rt/SpringbootCrudBoosterIT.java [hunk 1]
```diff
@@ -129,4 +129,12 @@ private void deployDatabaseUsingCLI() throws Exception {
     public void cleanup() throws Exception {
         cleanSampleTestRepository();
     }
+
+    @AfterClass
+    public static void deleteAllPods() throws InterruptedException {
+        OpenShiftClient aClient = new DefaultOpenShiftClient();
+        aClient.pods().inNamespace(aClient.getNamespace()).delete();
+        aClient.deploymentConfigs().inNamespace(aClient.getNamespace()).delete();
+        Thread.sleep(30 * 1000);
```
Comment (pepperbot) [inline rt/src/test/java/io/fabric8/maven/rt/SpringbootCrudBoosterIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

File: rt/src/test/java/io/fabric8/maven/rt/SpringbootHttpBoosterIT.java [hunk 2]
```diff
@@ -105,4 +103,12 @@ private void assertApplicationPodRoute(Route applicationRoute) throws Exception
     public void cleanup() throws Exception {
         cleanSampleTestRepository();
     }
+
+    @AfterClass
+    public static void deleteAllPods() throws InterruptedException {
+        OpenShiftClient aClient = new DefaultOpenShiftClient();
+        aClient.pods().inNamespace(aClient.getNamespace()).delete();
+        aClient.deploymentConfigs().inNamespace(aClient.getNamespace()).delete();
+        Thread.sleep(30 * 1000);
```
Comment (pepperbot) [inline rt/src/test/java/io/fabric8/maven/rt/SpringbootHttpBoosterIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

File: rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java [hunk 3]
```diff
@@ -112,4 +113,12 @@ private void assertThatWeServeAsExpected(Route applicationRoute) throws Exceptio
     public void cleanup() throws Exception {
         cleanSampleTestRepository();
     }
+
+    @AfterClass
+    public static void deleteAllPods() throws InterruptedException {
+        OpenShiftClient aClient = new DefaultOpenShiftClient();
+        aClient.pods().inNamespace(aClient.getNamespace()).delete();
+        aClient.deploymentConfigs().inNamespace(aClient.getNamespace()).delete();
+        Thread.sleep(30 * 1000);
```
Comment (pepperbot) [inline rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

File: rt/src/test/java/io/fabric8/maven/rt/VertxConfigmapBoosterIT.java [hunk 4]
```diff
@@ -141,4 +136,12 @@ private void editConfigMapResourceForApp(String configMapName) throws Exception
     public void cleanup() throws Exception {
         cleanSampleTestRepository();
     }
+
+    @AfterClass
+    public static void deleteAllPods() throws InterruptedException {
+        OpenShiftClient aClient = new DefaultOpenShiftClient();
+        aClient.pods().inNamespace(aClient.getNamespace()).delete();
+        aClient.deploymentConfigs().inNamespace(aClient.getNamespace()).delete();
+        Thread.sleep(30 * 1000);
```
Comment (pepperbot) [inline rt/src/test/java/io/fabric8/maven/rt/VertxConfigmapBoosterIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

File: rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java [hunk 5]
```diff
@@ -140,4 +132,12 @@ private void editConfigMapResourceForApp(String configMapName, String messagePro
     public void cleanup() throws Exception {
         cleanSampleTestRepository();
     }
+
+    @AfterClass
+    public static void deleteAllPods() throws InterruptedException {
+        OpenShiftClient aClient = new DefaultOpenShiftClient();
+        aClient.pods().inNamespace(aClient.getNamespace()).delete();
+        aClient.deploymentConfigs().inNamespace(aClient.getNamespace()).delete();
+        Thread.sleep(30 * 1000);
```
Comment (pepperbot) [inline rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

File: rt/src/test/java/io/fabric8/maven/rt/VertxHealthchecksBoosterIT.java [hunk 6]
```diff
@@ -134,4 +134,12 @@ private boolean isApplicationUpAndRunning(String hostUrl) throws Exception {
     public void cleanup() throws Exception {
         cleanSampleTestRepository();
     }
+
+    @AfterClass
+    public static void deleteAllPods() throws InterruptedException {
+        OpenShiftClient aClient = new DefaultOpenShiftClient();
+        aClient.pods().inNamespace(aClient.getNamespace()).delete();
+        aClient.deploymentConfigs().inNamespace(aClient.getNamespace()).delete();
+        Thread.sleep(30 * 1000);
```
Comment (pepperbot) [inline rt/src/test/java/io/fabric8/maven/rt/VertxHealthchecksBoosterIT.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)

**Comment by piyush1594** [comment]
[merge]
