### PR TITLE
Fix #1715: ApplyService#applyProjectRequest should be (truly) idempotent

### LINKED ISSUE #1715: ApplyService#applyProjectRequest should be (truly) idempotent
### Description

It seems like the method [ApplyService#applyProjectRequest](https://github.com/fabric8io/fabric8-maven-plugin/blob/721c960ffaf8e56fd713e170594f9b9ea352bed7/core/src/main/java/io/fabric8/maven/core/service/ApplyService.java#L1073) isn't truly idempotent - and I think the method name applies that it should be. It is close, but no cigar. If the method is invoked when a POST ProjectRequest is already in process by Openshift, but **before** the Project/Namespace actually exists, it will fail - because Openshift returns HTTP 409 when trying to POST ProjectRequest.

Somehow this bug is only noticeable when you are creating RoleBinding and BuildConfig resources. Why this happens becomes apparent if you look at the callers to the method:
````
ApplyService.applyProject(Project)  (io.fabric8.maven.core.service)
    ApplyMojo.executeInternal()  (io.fabric8.maven.plugin.mojo.build)
ApplyService.applyNamespace(String, Map<String, String>)  (io.fabric8.maven.core.service)
    ApplyService.applyNamespace(String)  (io.fabric8.maven.core.service)
        ApplyMojo.executeInternal()  (io.fabric8.maven.plugin.mojo.build)
        ApplyService.getNamespace(HasMetadata)  (io.fabric8.maven.core.service)
        ApplyService.applyRoleBinding(RoleBinding, String)  (io.fabric8.maven.core.service)
        ApplyService.applyBuildConfig(BuildConfig, String)  (io.fabric8.maven.core.service)
````
### Info

* f-m-p version : 4.2.0 (and same behavior with HEAD of master; 4.3-SNAPSHOT)
* Maven version (`mvn -v`) : 3.5.3 and also 3.6.1 (but I think it is irrelevant)
* Kubernetes / OpenShift setup and version : Openshift 3.11

### How to reproduce

* Prerequisite: Openshift mode

1. Create a simple Maven project with a single RoleBinding resource
1. Run mvn fabric8:resource-apply

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #1715

### CODE REVIEW

File: core/src/main/java/io/fabric8/maven/core/service/ApplyService.java [hunk 1]
```diff
@@ -1071,6 +1075,9 @@ public boolean applyProject(Project project) {
      * Returns true if the ProjectRequest is created
      */
     public boolean applyProjectRequest(ProjectRequest entity) {
+        // Check whether project creation attempted before
+        if (projectsCreated.contains(getName(entity)))
+            return true;
```
Comment (erikgb) [inline core/src/main/java/io/fabric8/maven/core/service/ApplyService.java]: According to the method signature, I think the return value should be false if projectsCreated contains getName(entity)

Comment (rohanKanojia) [reply core/src/main/java/io/fabric8/maven/core/service/ApplyService.java]: Nice catch! Thanks :+1:

File: core/src/main/java/io/fabric8/maven/core/service/ApplyService.java [hunk 2]
```diff
@@ -1071,6 +1075,9 @@ public boolean applyProject(Project project) {
      * Returns true if the ProjectRequest is created
      */
     public boolean applyProjectRequest(ProjectRequest entity) {
+        // Check whether project creation attempted before
+        if (projectsCreated.contains(getName(entity)))
```
Comment (dev-gaur) [inline core/src/main/java/io/fabric8/maven/core/service/ApplyService.java]: @rohanKanojia curly brackets, please!
