### PR TITLE
Fix #286 by adding a registry option

### LINKED ISSUE #286: kubernetes.yml doesn't include the registry prefix
Just been updating the fabric8 docs and need to check the workflow for f-m-p...

If I generate a springboot quickstart and deploy it on a kubernetes cluster (not minikube) I add the `fabric8:push` goal which does push the image but the pod fails to start and it can't find the image, the registry prefix was never added to the kubernetes.yml

to recreate (registry is behind VPN sorry incase others want to recreate)

```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.2:generate -Dfilter=io.fabric8:spring-boot-camel-archetype -DgroupId=my.test -DartifactId=fabric8-test-project
cd fabric8-test-project
mvn clean fabric8:run  -Ddocker.push.registry=fabric8-docker-registry.default.beast.fabric8.io
```

```
kubectl get pods
fabric8-test-project-2364102176-hjgtf      0/1       ErrImagePull       0          7s
```

```
kubectl describe pod fabric8-test-project-2364102176-hjgtf 
Failed to pull image "test/fabric8-test-project:latest": Error: image test/fabric8-test-project:latest not found
```

Checking the `./target/classes/META-INF/fabric8/kubernetes.yml` shows the registry isn't added to the image name

```
        containers:
          image: "test/fabric8-test-project:latest"
```

### PR DESCRIPTION
**Pull request by nicolaferraro**
I think this should be sufficient to use a registry in the docker image. The image can be tagged using the full name (with the registry) and used also in local mode as is, so the registry can be provided as command line option or configured in the pom.xml without issues.

@rhuss, can you give a quick look?

### CODE REVIEW

**Comment by nicolaferraro** [comment]
This should fix #286.

File: generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java [hunk 1]
```diff
@@ -64,7 +65,10 @@
         from,
 
         // Base image mode (only relevant for OpenShift)
-        fromMode;
+        fromMode,
+
+        // Optional registry
+        registry;
```
Comment (pepperbot) [inline generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java]: CRITICAL Rename this constant name to match the regular expression '^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00115)

**Comment by rhuss** [comment]
If I remember right, the issue is not so much about that the image has the proper prefix when its generated, but when it is referenced in the resource descriptors (e.g. when added by an enricher). There the registry prefix is still missing there.

**Comment by nicolaferraro** [comment]
Yeah, there's a unused registry property in the `ImageConfiguration` and it's true that it is not read. But sadly it's also [not settable through the builder](https://github.com/fabric8io/docker-maven-plugin/blob/2bb001d7ea9c0d3dba6cf5f5f495635cf163a2af/src/main/java/io/fabric8/maven/docker/config/ImageConfiguration.java#L34).

This works, as shown by the IT test. To properly fix it I'll add that property to the d-m-p builder.

**Comment by rhuss** [comment]
thanks ! btw, I can do a d-m-p release rather quickly.

**Comment by nicolaferraro** [comment]
Ok, so. Thanks!

**Comment by rhuss** [comment]
@nicolaferraro fyi, d-m-p 0.22.1 has been released.

**Comment by nicolaferraro** [comment]
Upgraded to latest d-m-p and changed impl

File: core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java [hunk 2]
```diff
@@ -122,7 +135,7 @@ private SecurityContext createSecurityContext(ResourceConfig config) {
     private List<ContainerPort> getContainerPorts(ImageConfiguration imageConfig) {
         BuildImageConfiguration buildConfig = imageConfig.getBuildConfiguration();
         List<String> ports = buildConfig.getPorts();
-        if (ports != null) {
+        if (ports != null && ports.size() > 0) {
```
Comment (pepperbot) [inline core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java]: MAJOR Remove this expression which always evaluates to "true" [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2589)
MINOR Use isEmpty() to check whether the collection is empty or not. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1155)

**Comment by nicolaferraro** [comment]
[merge]
