### PR TITLE
Fixes #1130 Application redeployment is getting failed on OpenShift v3.7.0

### LINKED ISSUE #1130: application redeployment is getting failed for OpenShift v3.7.0
### Description
If f8-m-p redeploy the existing application on OpenShift v3.7 then Deployment is not happening correctly.
Its unable to pull the images and status appears ImgPullErr for a long time. After some time with 4-5 retries, it's able to pull the image and deployment happen.

### Info
This might be an issue with F8-M-P or OpenShift.

* f-m-p version : v3.5.34 
* Maven version (`mvn -v`) :
```

```
* Kubernetes / OpenShift setup and version : OpenShift v3.7.0

* If it's a bug, how to reproduce :
- deploy the application using `mvn install or mvn fabric8:deploy`
- again invoke `mvn insall or mvn fabric8:deploy`

* Sample project : *[GitHub Clone URL]* : https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/spring-boot

### PR DESCRIPTION
**Pull request by rohanKanojia**
+ Added a workaround to deal with ImageTriggers.
+ Added flag fabric8.openshift.trimImageInContainerSpec which would trim
  image in container spec

#1130

### CODE REVIEW

File: plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java [hunk 1]
```diff
@@ -50,7 +50,7 @@ public DeploymentOpenShiftConverter(PlatformMode mode, Long openshiftDeployTimeo
     }
 
     @Override
-    public HasMetadata convert(HasMetadata item) {
+    public HasMetadata convert(HasMetadata item, boolean trimImageInContainerSpec) {
```
Comment (pepperbot) [inline plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java]: CRITICAL Refactor this method to reduce its Cognitive Complexity from 49 to the 15 allowed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3776)

**Comment by mojsha** [comment]
Can you add the possibility of setting automatic=false on the ImageTrigger? This would be much appreciated as we need the Image Trigger to resolve ImageStreamTag for the image, but do not want automatic re-deployment based on the ImageTrigger.

**Comment by rohanKanojia** [comment]
@mojsha : Yes, I think it's possible. Could you please file an issue for that and assign it to me?

**Comment by mojsha** [comment]
@rohanKanojia: Done https://github.com/fabric8io/fabric8-maven-plugin/issues/1177, but I could not assign it to you.

**Comment by rohanKanojia** [comment]
@hrishin : I think that during the build, we're don't know whether it's deployment scenario or redeployment scenario. Fabric8 maven plugin does a PUT of deployment config, so deploy or redeploy it's the same thing. Here we're just avoiding the update in container image spec, which was triggering redeployments. ImageTrigger would automatically inject the image into it.

**Comment by pradeepto** [comment]
@rohanKanojia @hrishin Did we run all required tests after this merge?
