### PR TITLE
Fix #1019: Custom Liveness/Readiness probes are not being created

### LINKED ISSUE #1019: Custom liveness/readiness probes are not being created
The plugin should be already configured to create liveness/readiness probes from custom user definition, as in the following example:

```
<resources>
   <readiness>
      <getUrl>/monitor/</getUrl>
   </readiness>
</resources>
```

Anyway no probes seem to be generated by this configuration.
We should:
- fix the issue (see discussion in #1014)
- create an integration test to avoid regression
- document the feature in the doc

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fix #1019: Added CustomProbeEnricher for adding probes via XML config

### CODE REVIEW

File: enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/CustomProbeEnricher.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+                        }
+                    }
+
+                    ProbeConfig livenessProbeConfig = resourceConfig.getLiveness();
+                    if (livenessProbeConfig != null) {
+                        Probe livenessProbe = probeHandler.getProbe(livenessProbeConfig);
+                        if (livenessProbe != null) {
+                            containerBuilder.withLivenessProbe(livenessProbe);
+                        }
+                    }
```
Comment (lordofthejars) [inline enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/CustomProbeEnricher.java]: I think we could create a method which returns the `Probe`.

```java
getProbe(ProbeConfig pc) {
  if (pc != null) {
    return  probeHandler.getProbe(pc);
  }
  return null;
}
```

And then it is called twice:

```java
containerBuilder.withLivenesssProve(getProbe(resourceConfig.getLiveness())
```

File: enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/CustomProbeEnricher.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+    @Override
+    public void addMissingResources(KubernetesListBuilder builder) {
+        builder.accept(new TypedVisitor<ContainerBuilder>() {
+            @Override
+            public void visit(ContainerBuilder containerBuilder) {
+                try {
+                    ResourceConfig resourceConfig = getConfiguration().getResource().get();
+
+                    Probe readinessProbe = getProbe(resourceConfig.getReadiness());
+                    if (readinessProbe != null) {
```
Comment (lordofthejars) [inline enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/CustomProbeEnricher.java]: Is this null check really necessary? I mean I think we can just call the `withXXXProbe` directly since by default its value is null, we are just setting again a null.

File: enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/CustomProbeEnricherTest.java [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+        // Enrich
+        CustomProbeEnricher enricher = new CustomProbeEnricher(context);
+        KubernetesListBuilder builder = getPodTemplateList();
+        enricher.addMissingResources(builder);
+
+        // Validate that the generated resource contains
+        KubernetesList list = builder.build();
+
+        String json = ResourceUtil.toJson(list.getItems().get(0));
+        System.out.println(json);
```
Comment (dev-gaur) [inline enricher/standard/src/test/java/io/fabric8/maven/enricher/standard/CustomProbeEnricherTest.java]: forgot to omit this?

File: enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java [hunk 4]
```diff
@@ -97,11 +97,26 @@ public DefaultControllerEnricher(MavenEnricherContext buildContext) {
...
+                    .withServiceAccount(resourceConfig.getServiceAccount())
                     .withReplicas(Configs.asInt(getConfig(Config.replicaCount)))
                     .build();
+        } else {
+            config = new ResourceConfig.Builder()
+                    .controllerName(name)
+                    .imagePullPolicy(getConfig(Config.pullPolicy))
+                    .withReplicas(Configs.asInt(getConfig(Config.replicaCount)))
+                    .build();
+        }
```
Comment (rhuss) [inline enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java]: would do sth like which makes it less redundant

```java
configBuilder = new ResourceConfig.Builder().controllerName(name)...;
if (resourceConfig != null) {
  configBuilder.volumes(...)...;

}

config = configBuilder.build();
```

Comment (rhuss) [reply enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java]: Sorry to bother you again, but what do you think about using a `ResourceConfig.Builder(ResourceConfig)` constructor which makes a deep copy of the given argument and then uses this as the internal resource object which is handed out later. That way, we can add new fields to ResourceConfig without bothering of enrichers using it (they get automatically the new fields initialized).
https://github.com/fabric8io/docker-maven-plugin/blob/38eba5ffa6920ea0bd24a1cc03c5c7224a26d4f4/src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java#L323-L329 how this is done for the BuildConfiguration.


See e.g.

File: core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java [hunk 5]
```diff
@@ -154,6 +154,29 @@ public ConfigMap getConfigMap() {
     public static class Builder {
         private ResourceConfig config = new ResourceConfig();
 
+        public Builder() { }
+
+        public Builder(ResourceConfig config) {
+            if(config != null) {
+                this.config.env = config.getEnv().orElse(null);
+                this.config.controllerName = config.getControllerName();
```
Comment (rhuss) [inline core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java]: Thanks, I think this is good enough (although its not really a complete deep-copy, as you would have to create new collections, too)
