### PR TITLE
Fix #1312 : Container name should not be generated from maven group Id

### LINKED ISSUE #1312: Container name should not be generated from maven group Id
### Description

When generating Kubernetes configurations, if username is omitted then maven group Id is inserted instead. Maven group id's often have periods, which are illegal characters in Kubernetes container names. Therefore, defaulting to an unmodified group ID seems like the wrong thing to do. Either remove the periods, or default to something else.

The erroneous function is extractContainerName in KubernetesResourceUtil. Decompiled, roughly:

```
    private static String extractImageUser(String image, MavenProject project) {
        ImageName name = new ImageName(image);
        String imageUser = name.getUser();
        return imageUser != null ? imageUser : project.getGroupId();
    }
```

### Info

* f-m-p version : 3.5.40
* Maven version (`mvn -v`) : Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
```

```
* Kubernetes / OpenShift setup and version : minikube version: v0.27.0
* If it's a bug, how to reproduce : create a maven project with a period in the group Id, and configure the plugin as follows:

```
                <configuration>
                    <registry>registry.gitlab.com/deltavstudios/flightcontrol</registry>
                    <images>
                        <image>
                            <!-- I am using a private registry here -->
                            <name>192.168.99.100:32449/%a:%l</name>
                            <build>
                               <!-- whatever -->
                            </build>
                        </image>
                    </images>
                </configuration>
```

### PR DESCRIPTION
**Pull request by rohanKanojia**
#1312

### CODE REVIEW

**Comment by rohanKanojia** [comment]
@nicolaferraro @hrishin : Could you please review whenever you get time?

File: core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java [hunk 1]
```diff
@@ -402,7 +404,17 @@ public static String extractContainerName(MavenProject project, ImageConfigurati
...
-        return imageUser != null ? imageUser : project.getGroupId();
+        String projectGroupId = project.getGroupId();
+        if(imageUser != null) {
+            return imageUser;
+        } else {
+            if(projectGroupId == null || projectGroupId.matches(CONTAINER_NAME_REGEX)) {
+                return projectGroupId;
+            }
+            else {
+                return projectGroupId.replaceAll("[^a-zA-Z0-9]", "");
```
Comment (hrishin) [inline core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: the regex `[^a-zA-Z0-9]` would also replace `-` which is desired?

File: core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java [hunk 2]
```diff
@@ -402,7 +404,17 @@ public static String extractContainerName(MavenProject project, ImageConfigurati
...
-        return imageUser != null ? imageUser : project.getGroupId();
+        String projectGroupId = project.getGroupId();
+        if(imageUser != null) {
+            return imageUser;
+        } else {
+            if(projectGroupId == null || projectGroupId.matches(CONTAINER_NAME_REGEX)) {
+                return projectGroupId;
+            }
+            else {
+                return projectGroupId.replaceAll("[^a-zA-Z0-9-]", "");
```
Comment (rhuss) [inline core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: This replacement still does not ensure that a name does not start or end with a `-`. Ok, a groupId propably never starts with a minus, but maybe it could end with one ?

I would add something like `.replace("^-*(.*)-*$","\\1")` ...

**Comment by rhuss** [comment]
@hrishin if the fix is good enough for you, could you please approve the PR ? thx!

File: core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java (hunk 2 above)
Comment (rohanKanojia) [reply core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: Sorry, please correct me if I'm wrong. I tested my regex with groupId ending with a `-`, I think it handles. Plus how does your regex trims `.` from groupId? Does `replace` work with regex? I tried your regex with `replaceAll` but it seems to be replacing everything with 1

Comment (rhuss) [reply core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: @rohanKanojia I mean to add the regexp I suggest in _addition_ to yours of course (and it was not tested, therefore that _something like_ ...)

```
projectGroupId.replaceAll("[^a-zA-Z0-9-]", "").replaceFirst("^-*(.*)-*$","\\1")
```

The idea is to remove leading and trailing `-` from the name as these are not allowed.

File: core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java [hunk 3]
```diff
@@ -402,7 +404,19 @@ public static String extractContainerName(MavenProject project, ImageConfigurati
...
+        String projectGroupId = project.getGroupId();
+        if(imageUser != null) {
+            return imageUser;
+        } else {
+            if(projectGroupId == null || projectGroupId.matches(CONTAINER_NAME_REGEX)) {
+                return projectGroupId;
+            }
+            else {
+                return projectGroupId.replaceAll("[^a-zA-Z0-9-]", "")
+                        .replaceFirst("^-", "\\1")
```
Comment (rhuss) [inline core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: Are you sure that this works ? You have no capturing group, so what should `\1` refer to ? Actually you could use `.replaceAll("^-*","")` if you want to do it two steps.

Comment (rohanKanojia) [reply core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: I tested it on groupIds like `io.fabric8-test-`, `io.fabric8-test-` and `-io.fabric8-test-`, Sorry I'm not an expert of regexes so might be doing some  mistake. We can replace `-` with any character in the desired container characters range, I just thought replacing it with `1`. Since you also suggested this in previous comment.

I tried your regex also i.e `projectGroupId.replaceAll("[^a-zA-Z0-9-]", "").replaceFirst("^-*(.*)-*$","\\1")` but it seems to be replacing everything with 1

Comment (rhuss) [reply core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: No, that `\1` references the content capturing group in the previous expression `(...)`. Its not "1" literally ;). Let me suggest a working solution and push it to your branch ...

Comment (rhuss) [reply core/src/main/java/io/fabric8/maven/core/util/KubernetesResourceUtil.java]: If you are interested how this works, look for "regular expression capturing group"

File: core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java [hunk 4]
```diff
@@ -143,6 +150,25 @@ public void invalidExtension() throws IOException {
...
+            result = "fabric8-maven-plugin-dummy";
+        }};
+
+        ImageConfiguration imageConfiguration = new ImageConfiguration.Builder()
+                .name("dummy-image")
+                .registry("example.com/someregistry")
+                .name("test")
+                .build();
+        String containerName = KubernetesResourceUtil.extractContainerName(project, imageConfiguration);
+        assertTrue(containerName.matches(KubernetesResourceUtil.CONTAINER_NAME_REGEX));
```
Comment (lordofthejars) [inline core/src/test/java/io/fabric8/maven/core/util/KubernetesResourceUtilTest.java]: assertj is already in classpath why not starting writing assertions using it?

**Comment by rhuss** [comment]
Looks good, thanks a lot ! And sorry for the confusion ...
