### PR TITLE
Fix #1162 : OpenShiftBuildServiceTest failing intermittently on CI

### LINKED ISSUE #1162: OpenshiftBuildServiceTest intermittently failing on jenkins.cd.test.fabric8.io
OpenshiftBuildServiceTest is continuously failing on fabric8 Jenkins CI. The problem is that it passes on the local machine but fails on Jenkins with this error:
```
Jan 17, 2018 1:24:28 PM okhttp3.mockwebserver.MockWebServer$3 processOneRequest
INFO: MockWebServer[59447] received request: GET /oapi/v1/namespaces/test/imagestreams/myapp HTTP/1.1 and responded: HTTP/1.1 200 OK
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.203 sec <<< FAILURE! - in io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest
testSuccessfulBuild(io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest)  Time elapsed: 10.828 sec  <<< ERROR!
io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: org.apache.maven.plugin.MojoExecutionException: Operation: [get]  for kind: [ImageStream]  with name: [myapp]  in namespace: [test]  failed.
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [ImageStream]  with name: [myapp]  in namespace: [test]  failed.
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: java.net.SocketTimeoutException: timeout
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
Caused by: java.net.SocketException: Socket closed
	at io.fabric8.maven.core.service.openshift.OpenshiftBuildServiceTest.testSuccessfulBuild(OpenshiftBuildServiceTest.java:148)
```
The complete build log can be found [here](https://jenkins.cd.test.fabric8.io/job/fabric8io/job/fabric8-maven-plugin/job/master/9/console). This test is blocking the deployment of fabric8 maven plugin to maven central(See #1158 ). In the deployment script, Github tags are being created first and then `mvn deploy` is being run after running tests; where this test creates problems.

### PR DESCRIPTION
**Pull request by rohanKanojia**
+ Handle Socket exception intermittently occurring in tests, and
  retry few times.
+ Added some logging in the test for better understanding of failure.

Fixes #1162

### CODE REVIEW

File: core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java [hunk 1]
```diff
@@ -139,18 +143,37 @@ public void init() throws Exception {
...
+                assertTrue(mockServer.getRequestCount() > 8);
+                collector.assertEventsRecordedInOrder("build-config-check", "new-build-config", "pushed");
+                collector.assertEventsNotRecorded("patch-build-config");
+                bTestComplete = true;
+            } catch (Fabric8ServiceException exception) {
+                Throwable rootCause = getRootCause(exception);
+                logger.warn("A problem encountered while running test {}, retrying..", exception.getMessage());
+                // Let's wait for a while, and then retry again
+                if (rootCause != null && rootCause instanceof IOException) {
+                    Thread.sleep(5 * 1000);
```
Comment (pepperbot) [inline core/src/test/java/io/fabric8/maven/core/service/openshift/OpenshiftBuildServiceTest.java]: MAJOR Remove this use of "Thread.sleep()". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2925)
