### PR TITLE
fix(timeoutSeconds): allow population on DeploymentConfig

### LINKED ISSUE #966: lets allow a `timeoutSeconds` to be configured on a `DeploymentConfig` for type `Recreate`
right now `timeoutSeconds` is ignored when turning a `Deployment` into a `DeploymentConfig` for kind `Recreate`

sample project that demonstrates the issue:
https://github.com/fabric8io/fabric8-platform/tree/master/apps/keycloak

if you build this without the associated PR for this issue then the `timeoutSeconds` on the `DeploymentConfig.spec.recreateParams.timeoutSeconds` gets ignored

This basically causes deployments of things like fabric8 to fail for folks who don't have super fast broadband - as we tend to use `Recreate` type for tenant apps for OpenShift Online

### PR DESCRIPTION
**Pull request by jstrachan**
fixes #966 to allow a timeoutSeconds to be specified on the Deployment and populated on a DeploymentConfig

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by jstrachan** [comment]
@rhuss does that test failure ring any bells? looks wacky - tests work fine locally https://ci.fabric8.io/job/fabric8-maven-plugin-pullreq/924/console

File: plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java [hunk 1]
```diff
@@ -86,10 +86,18 @@ public HasMetadata convert(HasMetadata item) {
...
-                if (openshiftDeployTimeoutSeconds != null && openshiftDeployTimeoutSeconds > 0 &&
-                        (Strings.isNullOrBlank(strategyType) || "Rolling".equals(strategyType))) {
-                    specBuilder.withNewStrategy().withType("Rolling").
-                        withNewRollingParams().withTimeoutSeconds(openshiftDeployTimeoutSeconds).endRollingParams().endStrategy();
+                if (openshiftDeployTimeoutSeconds != null && openshiftDeployTimeoutSeconds > 0) {
+                    if (Strings.isNullOrBlank(strategyType) || "Rolling".equals(strategyType)) {
+                        specBuilder.withNewStrategy().withType("Rolling").
+                            withNewRollingParams().withTimeoutSeconds(openshiftDeployTimeoutSeconds).endRollingParams().endStrategy();
+                    } else if (Strings.isNotBlank(strategyType)) {
+                        if (strategyType.equals("Recreate")) {
```
Comment (pepperbot) [inline plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java]: MAJOR A "NullPointerException" could be thrown; "strategyType" is nullable here. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2259)

**Comment by rhuss** [comment]
@jstrachan haven't seen this error before, but its because of a (temporary ?) sonarqube.com error. I would ignore it for now.

Let me review the PR later today.

**Comment by jstrachan** [comment]
@rhuss wacky - the test finished this time - guess it was a random CI fart :)

**Comment by jstrachan** [comment]
@rhuss I know you're busy and having fun in Barcelona but it'd be great to get a release of fmp out with this trivial fix (that only affects the few folks who use `Recreate` deployment strategy types)

File: plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java [hunk 2]
```diff
@@ -86,10 +86,18 @@ public HasMetadata convert(HasMetadata item) {
...
                 }
-                if (openshiftDeployTimeoutSeconds != null && openshiftDeployTimeoutSeconds > 0 &&
-                        (Strings.isNullOrBlank(strategyType) || "Rolling".equals(strategyType))) {
-                    specBuilder.withNewStrategy().withType("Rolling").
-                        withNewRollingParams().withTimeoutSeconds(openshiftDeployTimeoutSeconds).endRollingParams().endStrategy();
+                if (openshiftDeployTimeoutSeconds != null && openshiftDeployTimeoutSeconds > 0) {
+                    if (Strings.isNullOrBlank(strategyType) || "Rolling".equals(strategyType)) {
+                        specBuilder.withNewStrategy().withType("Rolling").
+                            withNewRollingParams().withTimeoutSeconds(openshiftDeployTimeoutSeconds).endRollingParams().endStrategy();
+                    } else if (Strings.isNotBlank(strategyType)) {
```
Comment (rhuss) [inline plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java]: Couldn't this check be placed top so that the 'rolling' check would benefit for this, too ?

Comment (rhuss) [inline plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java]: at least the code for "Rolling" and "Recreate" should be symmetrical.

Comment (rhuss) [inline plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java]: btw, I find it quite unfortunate that the kubernetes-client requires that kind of typing for the same thing. Would be much easier to set the timeout seconds directly for all strategy types. minor nit, though ;-)

Comment (jstrachan) [inline plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentOpenShiftConverter.java]: I just pushed a fix that tries to make the code look identical for `Rolling` and `Recreate` (other than we default to `Rolling` if no strategy is yet specified). 

Unfortunately the sub-types in kubernetes have no real polymorphism OOTB (e.g. the `Custom` strategy has no `timeoutSeconds` unlike `Rolling` and `Recreate`) - its common for them to be very different too (e.g. Volume types). Nor do we yet have polymorphic interfaces & builder APIs generated yet; that requires a much larger amount of work to be done on kubernetes-model which is outside of the fix for this issue ;)

**Comment by rhuss** [comment]
thanks !

[merge]
