### PR TITLE
Fix 1666: corrected back switchToDeployment flag functionality.

### LINKED ISSUE #1666: switchToDeployment does not work
### Info

* f-m-p version :4.1.0
* Maven version (`mvn -v`) :3.6.1
```
spring boot:2.0.6
label<switchToDeployment> It didn't work，The generated file contains parameters openshift.yaml “kind:DeploymentConfig”
```
* Kubernetes / OpenShift setup and version :v1.10/v3.10

### PR DESCRIPTION
**Pull request by dev-gaur**
fixes #1666

### CODE REVIEW

File: enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java [hunk 1]
```diff
@@ -52,10 +53,17 @@ public DeploymentConfigEnricher(MavenEnricherContext context) {
 
     @Override
     public void create(PlatformMode platformMode, KubernetesListBuilder builder) {
+
         if(platformMode == PlatformMode.openshift) {
-            for(HasMetadata item : builder.buildItems()) {
 
-                if(item instanceof Deployment) {
+            boolean switchToDeployment = false;
```
Comment (rohanKanojia) [inline enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java]: I would extract this to a method in BaseEnricher and a static constant for flag name. Since there is already `getValueFromConfig()` method available; this can make your work a bit easier

File: enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java [hunk 2]
```diff
@@ -59,6 +60,12 @@ public BaseEnricher(EnricherContext enricherContext, String name) {
         this.name = name;
     }
 
+    protected boolean useDeploymentforOpenShift() {
```
Comment (rohanKanojia) [inline enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java]: Do we really need this method? Can't we simply use getValueFromConfig directly?

Comment (dev-gaur) [reply enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java]: I checked for getValueFromConfig method. That method is specific is not a general utility, but a specific method used in VertxHealthCheckEnricher.

Comment (rohanKanojia) [reply enricher/api/src/main/java/io/fabric8/maven/enricher/api/BaseEnricher.java]: what? No. I think I wrote it to be used by all enrichers

File: enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java (hunk 1 above)
Comment (dev-gaur) [reply enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java]: Aah.. I made this changes in a bit of rush. Forgot about BaseEnricher and static constant.

Comment (rohanKanojia) [reply enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/openshift/DeploymentConfigEnricher.java]: np
