### PR TITLE
Fix bogus version in deployment selector.

### LINKED ISSUE #907: "matchLabels" section of generated kubernetes.yml always contains the version label
### Description
Since plugin version **3.2.27** the built artifact version is always included into "matchLabels" part of kubernetes selector.  The sample below is generated by 3.2.27 plugin version:
`"selector" : {
  "matchLabels" : {
     "project" : "my-project",
     "version" : "1.0.0",
     "group" : "com.my.group"
    }
}`
It leads to the problem with rolling updates of service in kubernetes, pods with previous versions are still alive and not replaced by fresh one. We were forced to downgrade plugin to **3.2.26** version, where this problem is absent and generated selector looks like:
`"selector" : {
  "matchLabels" : {
    "project" : "my-project",
    "group" : "com.my.group"
  }
}`
That solves rolling updates problem, but prevents us from any plugin updates, which is not good. Could you please make a fix for that problem or provide any suggestion how to avoid version label placing inside selector?
### Info

* Suffered f-m-p version :  3.2.27
* Working f-m-p version : 3.2.26

```
```
* Kubernetes / OpenShift setup and version : Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
* How to reproduce : Build the project by plugin version 3.2.27 and look into generated fabric8/kubernetes.yml, _kind: Deployment, section spec.selector.matchLabels_

### PR DESCRIPTION
**Pull request by rhuss**
Fixes #907.

### CODE REVIEW

File: it/src/it/simple/verify.groovy [hunk 1]
```diff
@@ -23,4 +24,11 @@ import io.fabric8.maven.it.Verify
           new File(basedir, sprintf("/expected/%s.yml",it)))
 }
 
+Map selector = Verify.readWithPath(
+        new File(basedir,"/target/classes/META-INF/fabric8/kubernetes/fabric8-maven-sample-zero-config-deployment.yml"),
+        "spec.selector.matchLabels")
+
+assertNotNull(selector)
+assertNull(selector.get("version"))
```
Comment (rhuss) [inline it/src/it/simple/verify.groovy]: Actually, in order to allow for robust tests, we can't check for required missing fields. We just ignore all extra fields (assuming that we typically want to check that something was added properly). So I think that this trade off is ok.

**Comment by rhuss** [comment]
[merge]
