### PR TITLE
Fixes #1185 : K8s: resource fragment containing compute resources for…

### LINKED ISSUE #1185: K8s: resource fragment containing compute resources for containers triggers a WARNING
### Description

Resource fragments in *deployment.yml* containing compute resources triggers a warning despite it is being deployed properly:

### Info

* f-m-p version : 3.5.34
* Maven version (`mvn -v`) : 3.3.9
* Kubernetes version : v1.8.4+coreos.0

### How to reproduce

Place resource fragment in *src/fabric8/deployment.yml*

```yaml
metadata:
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ${project.artifactId}-container
          resources:
            requests:
              cpu: 100m
              memory: 64Mi             
            limits:
              cpu: 200m
              memory: 512Mi       
```
Build:

```shell
> mvn clean install fabric8:build -P dev                           
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building message-service 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ message-service ---
[INFO] Deleting /home/david/dev/git/poc-message-service/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ message-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.34:resource (fmp) @ message-service ---
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-jboss-openjdk8-jdk:1.3 as base / builder
[INFO] F8: using resource templates from /home/david/dev/git/poc-message-service/src/main/fabric8
[INFO] F8: validating /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/openshift/message-service-srv-svc.yml resource
[INFO] F8: validating /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/openshift/message-service-deploymentconfig.yml resource

[WARNING] F8: Invalid Resource : /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/openshift/message-service-deploymentconfig.yml
[message=.spec.template.spec.containers[0].resources.requests.cpu: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.limits.cpu: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.requests.memory: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.limits.memory: string found, object expected, violation type=type]
[INFO] F8: validating /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/kubernetes/message-service-deployment.yml resource
[WARNING] F8: Invalid Resource : /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/kubernetes/message-service-deployment.yml
[message=.spec.template.spec.containers[0].resources.limits.memory: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.requests.memory: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.requests.cpu: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.limits.cpu: string found, object expected, violation type=type]
```

Deploy goal works properly and pod description show the selected resources:

```shell
Containers:
  message-service-container:
    Container ID:   docker://4578662f826bed474d606b1683b3673acda0d28af3b63a08e9d15d296ec2ae2a
    Image:          lpzdvd/message-service:1.0
    Image ID:       docker-pullable://lpzdvd/message-service@sha256:5726d126996944004245fd43e3e048cc30ccdbf378dc4a812f1c89ff97cb66bb
    Ports:          8080/TCP, 9779/TCP, 8778/TCP
    State:          Running
      Started:      Tue, 13 Feb 2018 17:35:40 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  512Mi
    Requests:
      cpu:     100m
      memory:  64Mi
```

### PR DESCRIPTION
**Pull request by rohanKanojia**
#1185 Added an IgnoreRule for warning

### CODE REVIEW

File: core/src/main/java/io/fabric8/maven/core/util/validator/IgnoreResourceMemoryLimitRule.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ * implied.  See the License for the specific language governing
+ * permissions and limitations under the License.
+ */
+
+package io.fabric8.maven.core.util.validator;
+
+import com.networknt.schema.ValidationMessage;
+
+public class IgnoreResourceMemoryLimitRule implements ValidationRule {
+    private final String type;
```
Comment (pepperbot) [inline core/src/main/java/io/fabric8/maven/core/util/validator/IgnoreResourceMemoryLimitRule.java]: BLOCKER Rename field "type" to prevent any misunderstanding/clash with field "TYPE" defined in interface "io.fabric8.maven.core.util.validator.ValidationRule". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1845)

File: core/src/main/java/io/fabric8/maven/core/util/validator/IgnorePortValidationRule.java [hunk 2]
```diff
@@ -3,19 +3,19 @@
...
- * Model to represent ignore validation rules as tuple of json tree path and constraint type
+ * Model to represent ignore validation rules as tuple of json tree path and constraint ruleType
  * for resource descriptor validations
  */
 public class IgnorePortValidationRule implements ValidationRule {
 
-    private final String type;
+    private final String ruleType;
 
     public IgnorePortValidationRule(String type) {
```
Comment (piyush1594) [inline core/src/main/java/io/fabric8/maven/core/util/validator/IgnorePortValidationRule.java]: Lets change this also to make this consistent

File: core/src/main/java/io/fabric8/maven/core/util/validator/IgnoreResourceMemoryLimitRule.java [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+ */
+
+package io.fabric8.maven.core.util.validator;
+
+import com.networknt.schema.ValidationMessage;
+
+public class IgnoreResourceMemoryLimitRule implements ValidationRule {
+    private final String ruleType;
+
+    public IgnoreResourceMemoryLimitRule(String aType) { this.ruleType = aType; }
```
Comment (piyush1594) [inline core/src/main/java/io/fabric8/maven/core/util/validator/IgnoreResourceMemoryLimitRule.java]: Lets change this also to make this consistent
