### PR TITLE
fixes #1044 regression of new validation code in 3.5.28

### LINKED ISSUE #1044: regresssion in 3.5.28 with new validation code
we're getting this NPE in fabric8-platform in `apps/ingress-nginx` when running `mvn fabric8:resource`:
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:resource (default-cli) on project ingress-nginx: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.5.28:resource failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:resource (default-cli) on project ingress-nginx: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.5.28:resource failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.5.28:resource failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at io.fabric8.maven.core.util.validator.ResourceValidator.geFileContent(ResourceValidator.java:169)
	at io.fabric8.maven.core.util.validator.ResourceValidator.validate(ResourceValidator.java:108)
	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.validateIfRequired(ResourceMojo.java:286)
	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.executeInternal(ResourceMojo.java:270)
	at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

A PR is on its way...

### PR DESCRIPTION
**Pull request by jstrachan**
lets avoid NPEs and avoid validating directories

### CODE REVIEW

File: core/src/main/java/io/fabric8/maven/core/util/validator/ResourceValidator.java [hunk 1]
```diff
@@ -103,13 +102,15 @@ private void setupIgnoreRules(ResourceClassifier target) {
      * @throws IOException
      */
     public int validate() throws ConstraintViolationException, IOException {
```
Comment (pepperbot) [inline core/src/main/java/io/fabric8/maven/core/util/validator/ResourceValidator.java]: MINOR Remove the declaration of thrown exception 'javax.validation.ConstraintViolationException' which is a runtime exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ARedundantThrowsDeclarationCheck)

**Comment by jstrachan** [comment]
I guess if we find a directory should we iterate through its files? Wasn't sure - just did that to avoid an unnecessary warning when trying to validate the `openshift` directory

**Comment by hrishin** [comment]
For the time being lets skip it because during validation we are providing directories of `Kubernetes` and `OpenShift` resources

File: plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java [hunk 2]
```diff
@@ -299,6 +293,12 @@ private void validateIfRequired(File resourceDir, ResourceClassifier classifier)
             } else {
                 log.warn("[[Y]]" + e.getMessage() + "[[Y]]");
             }
+        } catch (Throwable e) {
```
Comment (pepperbot) [inline plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java]: MAJOR Catch Exception instead of Throwable. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1181)
