### PR TITLE
Fixes #1003: adding fabric8.debug.suspend flag

### LINKED ISSUE #1003: fabric8:debug allow suspend y/n to be optionally specified via a property
it would be nice to enable suspend mode when debugging so that the JVM pauses and waits for the debugger to connect before starting; for cases where you wanna debug a failing JVM

### PR DESCRIPTION
**Pull request by nicolaferraro**
This requires the base image to support the env variable `JAVA_DEBUG_SUSPEND` (https://github.com/fabric8io-images/run-java-sh/pull/21 and other PRs to come for the base images).

Each run of `fabric8:deploy -Dfabric8.debug.suspend` restarts the pod, so a debugger can attach at startup. Readiness probes are disabled.

### CODE REVIEW

File: plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java [hunk 1]
```diff
@@ -185,13 +197,23 @@ public void onClose(KubernetesClientException e) {
...
-        throw new MojoExecutionException("Could not find a running pod with $" + envVarName + " = " + envVarValue);
+        throw new MojoExecutionException("Could not find a running pod with environment variables " + envVars);
     }
 
     private boolean isAddOrModified(Watcher.Action action) {
         return action.equals(Watcher.Action.ADDED) || action.equals(Watcher.Action.MODIFIED);
     }
 
+    private boolean podHasEnvVars(Pod pod, Map<String, String> envVars) {
+        for (String envVarName : envVars.keySet()) {
```
Comment (pepperbot) [inline plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java]: MAJOR Iterate over the "entrySet" instead of the "keySet". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2864)

File: plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java [hunk 2]
```diff
@@ -251,6 +273,23 @@ private boolean enableDebugging(HasMetadata entity, PodTemplateSpec template) {
                         container.setPorts(ports);
                         enabled = true;
                     }
+                    if (debugSuspend) {
+                        // Setting a random value to force pod restart
+                        this.debugSuspendValue = String.valueOf(new Random().nextLong());
+                        KubernetesResourceUtil.removeEnvVar(env, DebugConstants.ENV_VAR_JAVA_DEBUG_SUSPEND);
+                        KubernetesResourceUtil.setEnvVar(env, DebugConstants.ENV_VAR_JAVA_DEBUG_SUSPEND, this.debugSuspendValue);
```
Comment (rhuss) [inline plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java]: Shouldn't `KubernetesResourceUtil.setEnvVar()` overwrite an existing variable if already present ? I would prefer this over an explicit removeEnvVar before, so that its more aligned to common practice. Also, setEnvVar should also ensure that it does not add the same env var twice.

File: plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java [hunk 3]
```diff
@@ -251,6 +273,23 @@ private boolean enableDebugging(HasMetadata entity, PodTemplateSpec template) {
...
+                        container.setEnv(env);
+                        if (container.getReadinessProbe() != null) {
+                            log.info("Readiness probe will be disabled on " + getKind(entity) + " " + getName(entity) + " to allow attaching a remote debugger during suspension");
+                            container.setReadinessProbe(null);
+                        }
+                        enabled = true;
+                    } else {
+                        if (KubernetesResourceUtil.removeEnvVar(env, DebugConstants.ENV_VAR_JAVA_DEBUG_SUSPEND)) {
```
Comment (rhuss) [inline plugin/src/main/java/io/fabric8/maven/plugin/mojo/develop/DebugMojo.java]: Could you always set the variable with 'true', 'false' (and evaluate it accordingly in the startup script). This would simplify the code here (you don't need an "if" then, but set it always) and it makes it more explicit for the user within the container whether suspending is switched on or off (since the env var is always set).

**Comment by nicolaferraro** [comment]
[merge]
