### PR TITLE
Fixes #1042 Switch to using Deployments rather than DeploymentConfig on OpenShift when not using ImageStreams

### LINKED ISSUE #1042: switch to using Deployments rather than DeploymentConfig on OpenShift when not using ImageStreams
DeploymentConfig's are quite a bit worse to use than Deployments due to the extra deploy pods that sometimes timeout/fail, stay around, add confusion - whereas Deployments seem pretty rock solid! I've never seen a Deployment ever not deploy or timeout - whereas I've seen that happen lots with DCs.

So I wonder should we avoid DeploymentConfigs when not using ImageStreams on OpenShift? I guess we could make it a flag so folks could decide to keep DCs if they really want; but I'd have thought sticking with standard kubernetes resources OOTB sounds a nicer default (providing folks are not using ImageStreams)

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fabric8-maven-plugin should always use DeploymentConfigs if using ImageStreams; but if not we should probably default to Deployments.

### CODE REVIEW

File: plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java [hunk 1]
```diff
@@ -174,6 +175,8 @@
     @Parameter(property = "fabric8.build.strategy")
     private OpenShiftBuildStrategy buildStrategy = OpenShiftBuildStrategy.s2i;
 
+    @Parameter(property = "fabric8.build.switchToDeployment", defaultValue = "true")
```
Comment (hrishin) [inline plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java]: Would it be better to keep the default preference to `false`, so that existing users will not get surprising behavior :)
@jstrachan WDYT?
